---
title: "Figure 4"
author: "Zhenna Jiao"
date: "2024-03-04(last modified: `r Sys.Date()`)"
output: 
    prettydoc::html_pretty:
    theme: cayman
    highlight: github
---
## Load packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggbiplot)
library(ggplot2)
library(corrplot)
library(magrittr)
library(RColorBrewer)
library(stringr)
library(ggpubr)
library(ggrepel)
library(readxl)
library(ComplexHeatmap)
library(scales)
library(dplyr)
library(reshape2)
library(ggalluvial)
```

## Import the data 

```{r}
meta_df <- readRDS("~/methylation/project/EM_seq/data/metadata/meta_df.rds")
meta_scstage_df <- readRDS("~/methylation/project/EM_seq/data/metadata/meta_scstage_df.rds")
fig_proj <- "~/methylation/project/EM_seq/analysis/DMR_analysis/figures/fig4/"
sc_dat_dir <- "~/methylation/project/EM_seq/analysis/DMR_analysis/data/filter_sample/scstage_dmr_change/"
meta_df <- meta_df%>% mutate(sample_names=str_replace_all(sample_list,"-","."))
```

## Figure 4A Make a barplot for the top10 GO terms 

```{r,fig.width=20,fig.height=8}
## import data
fig4_dat <- "~/methylation/project/EM_seq/analysis/DMR_analysis/data/fig4_GO_data/"
smp_go_table <- read_excel(paste0(fig4_dat,"GO_Biological_Process_2023_table_filter_dmr (2).xlsx"))
smp_go_top10_df <- smp_go_table[1:11,c(1,3,4)]
smp_go_top10_df$log10p_adjust <- -log10(smp_go_top10_df$`Adjusted P-value`)
smp_go_top10_df$Term <- factor(smp_go_top10_df$Term, levels = rev(smp_go_top10_df$Term))
data <- smp_go_table[1:11,]

data <- data %>%
        mutate(
        Combined_score = data$`Combined Score`,
        EnrichmentFDR = -log10(data$`Adjusted P-value`),
        N_genes = sapply(strsplit(as.character(Genes), ";"), length)
        )

data <- data[data$EnrichmentFDR > 1.30103 ,]
plot <- ggplot(data, aes(x = reorder(Term, Combined_score), y = Combined_score)) +
        geom_point(aes(size = N_genes, color = EnrichmentFDR)) +
        scale_color_gradient(low = "blue", high = "red") +
        coord_flip() +
        labs(
        title = "Top10 GO term",
        x = "",
        y = "Combined score",
        color = "EnrichmentFDR",
        size = "Genes"
        ) +
        theme_minimal() +
        theme(axis.text.x = element_text(size = 15),
              axis.text.y = element_text(size = 15),
              axis.text = element_text(size = 15,colour = "black"),
              axis.line.x = element_line(size = 1,linetype = 1,colour = "black"),
              axis.line.y = element_line(size = 1,linetype = 1,colour = "black"),
              axis.title = element_text(size = 15,colour = "black"),
              legend.title = element_text(size = 15),
              legend.text = element_text(size = 15))
  
  plot
# ggsave(plot = plot,filename = paste0(fig_proj,"fig4A_filter_dmr_smp_GO_top10_p_20240722.pdf"),
#          device = "pdf",width = 15, height = 6)
  
```

## Figure 4B

```{r,fig.width=15,fig.height=10}
## import data
dat_dir <- "~/methylation/project/EM_seq/analysis/DMR_analysis/code/gene_anlyais/"
go_gene_4 <- read.csv(paste0(dat_dir,"Go4_genes_meth.csv"))

go4_gene_p <- go_gene_4[go_gene_4$p_adjust<0.05,]
order_name <- c( "DPYSL3","RAPGEF2", 
                 "NLGN1", 
                  "TENM3" ,"MAGI2","ROBO1","SLIT2","EPHA3","DDR2",
                 "NRXN1","CDH12","SLITRK6","FN1","PKP3","CDH9","POU4F1","CDH8","ADGRL3",
                 "SMARCB1","ARID1B","SMARCA2",
                  "KANK1","DCC","LPAR1" )
go_gene_4$Genes <- factor(go_gene_4$Genes, levels = order_name)
sorted_go_gene_4 <- go_gene_4 %>% arrange(Genes)
sorted_go_gene_4[,4:8] <- lapply(sorted_go_gene_4[,4:8],as.character)
sorted_go_gene_4$new_col <- apply(sorted_go_gene_4[,c(2,5,4,6)],1,function(x) paste(x,collapse = "_"))

## extract the data to do heatmap
heatmap_dat <- sorted_go_gene_4[,c(2,10:47)]
rownames(heatmap_dat) <- heatmap_dat$Genes

gp_mat <- heatmap_dat[,2:18]%>%as.matrix()
rownames(gp_mat) <- rownames(heatmap_dat)
gc_mat <- heatmap_dat[,19:39]%>%as.matrix()
rownames(gc_mat) <- rownames(heatmap_dat)
## annotation setting 
type_colors <- c("GC" = "#FB8D8D", "GP" = "#C0E1FF")
stage_colors <- c("Control" = "#63A6D0", "Early Stage" = "#F9A68A", "Advanced Stage" = "#D34447")

gender_colors <- c("Male" = "#AACBFE", "Female" = "#DE8686")

my_color=c("#4675FE","#F9F5C9","#FCA605")

row_groups <- c(rep("GO:0031346;GO:0031345", 2),
                rep("GO:0031346;GO:0034329",1),
                rep("GO:0031346",6),
                rep("GO:0034329",9),
                rep("GO:0045582",3),
               rep("GO:0031345",3))

row_promoter <- c(rep("No",10),"Yes",rep("No",12),"Yes")%>%as.factor()
ann_ht1 <- HeatmapAnnotation(Gender=meta_df$sc_gender[1:17],
                            Stage=meta_df$sc_stage[1:17],
                              Type=meta_df$sc_type[1:17],
                             annotation_name_side = "left",
                            annotation_name_gp = gpar(fontsize = 0),
                               col=list(Gender = gender_colors,
                                        Stage = stage_colors,
                                        Type = type_colors ))
                                  
                                 

ann_ht2 <- HeatmapAnnotation(Gender=meta_df$sc_gender[18:38],
                            Stage=meta_df$sc_stage[18:38],
 
                            Type=meta_df$sc_type[18:38],
                            col=list(Gender = gender_colors,
                                      Stage = stage_colors,
                                      Type = type_colors),
                                      annotation_name_side = "right")

row_promoter_col <- rowAnnotation(Promoter=row_promoter,col=list(Promoter=c("No"="#999999","Yes"="#F2F2F2")))
row_annots <- rowAnnotation(GO = row_groups,
                           col = list(GO = c("GO:0034329"="#2F7EBC",

                                             "GO:0031345"="#F96949",

                                             "GO:0031346"="#50B8DD",

                                              "GO:0045582"="#FCBC85",

                                             "GO:0031346;GO:0034329"="#77C8A6",

                                             "GO:0031346;GO:0031345"="#FCEBDE"
                                            )),
                           annotation_legend_param = list(
                             GO = list(
                               at = c("GO:0034329", "GO:0031345", "GO:0031346", "GO:0045582", 
                                      "GO:0031346;GO:0034329", "GO:0031346;GO:0031345"),
                               labels = c("Cell Junction Assembly", 
                                          "Negative Regulation Of Cell Projection Organization", 
                                          "Positive Regulation Of Cell Projection Organization", ## change
                                          "Positive Regulation Of T Cell Differentiation",
                                          "Positive Regulation Of Cell Projection Organization;Cell Junction Assembly", 
                                          "Positive Regulation Of Cell Projection Organization;Negative Regulation Of Cell Projection Organization")
                             )
                           ))
## do heatmap
heat_map_1 <- Heatmap(gp_mat,name="gp",
                      cluster_rows = T,
                      cluster_columns = T,
                      row_split = row_groups,
                     # right_annotation = row_annots,
                      top_annotation = ann_ht1,
                      show_column_names = F,
                     show_row_dend = F,
                     show_row_names = T,
                     row_title = NULL,
                     show_heatmap_legend = FALSE,
                     border_gp = gpar(col = "NA"),
                       col = colorRampPalette(my_color)(100),
                       na_col = "white",width =unit(4,"cm"),
                     height = unit(10,"cm")
                      )
heat_map_2 <- Heatmap(gc_mat,name="gc",
                      cluster_rows = T,
                      cluster_columns = T,
                      row_split = row_groups,
                      right_annotation =c(row_annots,row_promoter_col) ,
                      top_annotation = ann_ht2,
                      show_column_names = F,
                      show_row_dend = F,
                      show_row_names = T,
                       row_title = NULL,
                      col = colorRampPalette(my_color)(100),
                      na_col = "white",width = unit(4,"cm"),
                      height = unit(10,"cm"),
                      row_dend_side = "right")


p <- heat_map_1+heat_map_2
p
```

## Fig 4E  

```{r,fig.width=10,fig.height=8}
dat_dir_too <- "~/methylation/project/EM_seq/analysis/deconv_analysis/TAPS_data/data/"
# Tissue contribution ----
dat <- read.table(paste0(dat_dir_too,"sample_mixtures.csv"), header=TRUE, stringsAsFactors=FALSE, sep="\t")
dat.m <- melt(dat,id.vars=c("atlas_tissues"))
dat.m$atlas_tissues[dat.m$atlas_tissues %in% c("immature neutrophil","mature neutrophil")] <- "neutrophil"
dat.m$atlas_tissues[dat.m$atlas_tissues %in% c("immature conventional dendritic cell","mature conventional dendritic cell")] <- "dendritic cell"
a <- dat.m
dat.m <- aggregate(dat.m$value, by=list(Category=dat.m$variable, dat.m$atlas_tissues ), FUN = sum) %>% as.data.frame()
colnames(dat.m) <- c("variable","atlas_tissues","value")
dat.m$Type <- substr(dat.m$variable,1,2)
dat.m$Type <- recode(dat.m$Type,"sc"="Cancer","gp"="Benign")
tissue_group <- aggregate(dat.m$value, by=list(Category=dat.m$Type,dat.m$atlas_tissues ), FUN = mean) %>% as.data.frame()
colnames(tissue_group) <- c("status", "tissue" , "value")

stack_dat <- tissue_group
stack_dat$status <- as.factor(stack_dat$status)

stack_dat$tissue[stack_dat$value<=0.015] <- "Other"
  stack_dat <- aggregate(stack_dat$value, by=list(Category=stack_dat$status,stack_dat$tissue ), FUN = sum) %>% as.data.frame()
  colnames(stack_dat) <- c("status", "tissue", "value")
  stack_dat$value <- round(stack_dat$value,2) * 100
  stack_dat <- stack_dat[order(stack_dat$value),]
  tissue_level <- c("neutrophil", "spleen", "dendritic cell", "monocyte", "Thymus", "macrophage", "osteoclast", "Other",
                    "plasma_cell", "heart", "intestine", "liver", "lung", "naive_tcell")
  stack_dat$tissue <- factor(stack_dat$tissue,levels=rev(tissue_level))
  
mycolors <- rev(colorRampPalette(brewer.pal(12, "Paired"))(14))

p3 <- ggplot(stack_dat,aes(fill = tissue, y = value, x = status,label = value)) +
        geom_bar(position = "stack", stat = "identity",width = 0.5)+
        scale_fill_manual(values = mycolors) +
        geom_text(stat = "stratum", aes(stratum =tissue),size=0)+
        theme_classic()+
        ylab("Mean tissue contribution")+
        xlab("")+
        theme(axis.text = element_text(size = 10,colour = "black"),
              axis.title = element_text(size = 10,colour = "black"))
print(p3)
```

## Technical

```{r}
sessionInfo()
```

